# -*- coding: utf-8 -*-
"""Untitled43 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-xj_tN7Jan5lkt7NdhSksB31-ZPVbDLm
"""

import os
import requests
import csv
from bs4 import BeautifulSoup
from itertools import zip_longest
result = requests.get('https://www.dubizzle.com.eg/en/vehicles/cars-for-sale/q-cars/')
src = result.content
soup = BeautifulSoup(src, 'lxml')
titles = []
image_urls = []
prices = []
locations = []
description = []
links=[]
cars = soup.find_all('h2', {'class': 'a5112ca8'})
price = soup.find_all('span', {'class': '_95eae7db'})
picture_elements = soup.find_all('picture', {'class': '_219b7e0a'})
car_link_element = soup.find_all('div',{'class':'ee2b0479'})

for picture_element in picture_elements:
    img_tag = picture_element.find('img')
    image_urls.append(img_tag['src'])

for i in range(len(cars)):
    titles.append(cars[i].text)
    prices.append(price[i].text)
    links.append('https://www.dubizzle.com.eg/' + car_link_element[i].find('a').attrs['href'])
for link in links:
  res=requests.get(link)
  scr=res.content
  soup=BeautifulSoup(scr,'lxml')
  des=soup.find_all('div',{'class':'_0f86855a'})
  for i in range(len(des)):
    description.append(des[i].find('span').text +'\n')
#for i in range(len(des)):
  #description.append(des[i].find('span').text)

# Create the "allimag" folder if it doesn't exist
folder_name = 'allimag'
if not os.path.exists(folder_name):
    os.makedirs(folder_name)

# Download and save images
images = []
for i, image_url in enumerate(image_urls):
    response = requests.get(image_url)
    if response.status_code == 200:
        # Get the content of the response (image file data)
        image_data = response.content

        # Save the image file in the "allimag" folder
        file_name = f'{folder_name}/image{i}.jpg'
        with open(file_name, 'wb') as file:
            file.write(image_data)
        images.append(file_name)

data = zip_longest(titles, prices, images,description,links)

with open('output.csv', 'w', encoding='utf-8-sig', newline='') as myfile:
    wr = csv.writer(myfile)
    wr.writerow(['Title', 'Price', 'Image','description','links'])
    wr.writerows(data)



